/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ExamContract__factory } from "./ExamContract__factory";
export { IExamContract__factory } from "./IExamContract__factory";
