/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ExamContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExamContract__factory>;
    getContractFactory(
      name: "IExamContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IExamContract__factory>;
    getContractFactory(
      name: "Multicall",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Multicall__factory>;

    getContractAt(
      name: "ExamContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExamContract>;
    getContractAt(
      name: "IExamContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IExamContract>;
    getContractAt(
      name: "Multicall",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Multicall>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
