/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ExamContract } from "./ExamContract";
export type { IExamContract } from "./IExamContract";
export type { Multicall } from "./Multicall";
export * as factories from "./factories";
export { ExamContract__factory } from "./factories/ExamContract__factory";
export { IExamContract__factory } from "./factories/IExamContract__factory";
export { Multicall__factory } from "./factories/Multicall__factory";
