@startuml participant

hide unlinked
skinparam wrapWidth 150

!include<logos/ethereum>
!include<office/Users/user>
!include<tupadr3/font-awesome-5/university>
!include<material/school>

participant "<$user>\nStudent" as stu
participant "<$ma_school>\nProfessor" as pro
participant "<$university>\nUniversity" as uni
participant "<$ethereum*.6>\nSmart contract" as eth

@enduml